apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- components/build-service/base
- components/managed-gitops/base
- components/service-provider-integration-oauth/base
- components/service-provider-integration-operator/base
kind: Kustomization
resources:
- common-storage-pvc.yaml
